export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Signup } from './Signup'
export { default as PostsPag } from './PostsPage'
export { default as PostPage } from './PostPage'
export { default as CreatePost } from './CreatePost'